---
- name: crm_espo op vm 
  hosts: localhost
  become: yes
  connection: local
  vars:
    espocrm_db_name: crmespo
    espocrm_db_user: crm_gebruiker
    espocrm_db_password: emmaoudhof
    espocrm_db_host: localhost
    espocrm_site_url: "http://{{ ansible_default_ipv4.address }}"
    espocrm_admin_user: admin
    espocrm_admin_password: admin
    espocrm_admin_email: admin@admin.com
    ansible_python_interpreter: /usr/bin/python3
    mysql_root_password: emmaoudhof

  tasks:
  - name: Systeem updaten en upgraden
    apt:
      update_cache: yes
      upgrade: dist
    ignore_errors: yes
    # Deze taak zorgt ervoor dat het systeem wordt geüpdatet en dat er een distributie-upgrade wordt uitgevoerd

  - name: Apache2 installeren
    apt:
      name: apache2
      state: aanwezig
    ignore_errors: yes
    # Installeert de Apache2 webserver

  - name: MySQL-server installeren
    apt:
      name: mysql-server
      state: aanwezig
    ignore_errors: yes
    # Installeert de MySQL-server voor databasebeheer

  - name: PHP en vereiste modules installeren
    apt:
      name:
        - php
        - libapache2-mod-php
        - php-mysql
        - php-curl
        - php-gd
        - php-imagick
        - php-mbstring
        - php-xml
        - php-xmlrpc
        - php-zip  
      state: aanwezig
    ignore_errors: yes
    # Installeert PHP en de benodigde modules voor EspoCRM

  - name: Installeer unzip pakket
    apt:
      name: unzip
      state: aanwezig
    ignore_errors: yes
    # Installeert het 'unzip' pakket om bestanden uit te pakken

  - name: EspoCRM MySQL-database en gebruiker aanmaken
    shell: |
      mysql -e "CREATE DATABASE IF NOT EXISTS {{ espocrm_db_name }};"
      mysql -e "CREATE USER IF NOT EXISTS '{{ espocrm_db_user }}'@'localhost' IDENTIFIED BY '{{ espocrm_db_password }}';"
      mysql -e "GRANT ALL PRIVILEGES ON {{ espocrm_db_name }}.* TO '{{ espocrm_db_user }}'@'localhost';"
      mysql -e "FLUSH PRIVILEGES;"
    ignore_errors: no
    # Maakt de EspoCRM MySQL-database en bijbehorende gebruiker aan

  - name: EspoCRM downloaden
    get_url:
      url: https://www.espocrm.com/downloads/EspoCRM-8.4.1.zip
      dest: /var/www/html/EspoCRM-8.4.1.zip
    ignore_errors: yes
    # Downloadt het EspoCRM pakket van de officiële website

  - name: EspoCRM uitpakken
    unarchive:
      src: /var/www/html/EspoCRM-8.4.1.zip
      dest: /var/www/html/
      remote_src: yes
    # Pakt het EspoCRM archief uit naar de webroot

  - name: Verplaats alle bestanden van EspoCRM-8.4.1 naar /var/www/html
    shell: |
      mv /var/www/html/EspoCRM-8.4.1/* /var/www/html/
      rm -rf /var/www/html/EspoCRM-8.4.1
    ignore_errors: no
    # Verplaatst de uitgepakte bestanden naar de webroot en verwijdert de map

  - name: Stel juiste permissies in voor EspoCRM-bestanden en mappen
    file:
      path: /var/www/html
      owner: www-data
      group: www-data
      mode: '0755'
      recurse: yes
    # Wijzigt de bestandseigenaar naar www-data en stelt de juiste rechten in voor de webroot

  - name: Schrijfbare permissies instellen voor specifieke EspoCRM-mappen
    file:
      path: "/var/www/html/{{ item }}"
      owner: www-data
      group: www-data
      mode: '0775'
      recurse: yes
    loop:
      - data
      - custom
      - client
    # Zorgt ervoor dat bepaalde EspoCRM-mappen schrijfbaar zijn voor www-data

  - name: Apache herschrijfmodule inschakelen
    command: a2enmod rewrite
    # Schakelt de mod_rewrite module in voor Apache

  - name: Apache configureren voor EspoCRM
    blockinfile:
      path: /etc/apache2/sites-available/000-default.conf
      marker: "# {mark} ANSIBLE MANAGED BLOCK"
      block: |
        DocumentRoot /var/www/html/public

        <Directory /var/www/html/public/>
            AllowOverride All
            Require all granted
        </Directory>

        Alias /client /var/www/html/client

        <Directory /var/www/html/client/>
            AllowOverride All
            Require all granted
        </Directory>
    # Past de Apache-configuratie aan om EspoCRM te ondersteunen

  - name: Systemd herladen
    command: systemctl daemon-reload
    # Herlaadt systemd om wijzigingen door te voeren

  - name: Apache herstarten
    service:
      name: apache2
      state: herstart
    # Start de Apache-webserver opnieuw

  - name: Controleren of EspoCRM toegankelijk is
    uri:
      url: "{{ espocrm_site_url }}"
      status_code: 200
    ignore_errors: yes
    # Controleert of de EspoCRM-website correct functioneert

  handlers:
    - name: Apache herstarten
      service:
        name: apache2
        state: herstart
      # Handler om Apache opnieuw te starten wanneer nodig
