---
- name: Zabbix-agent installatie en configuratie
  hosts: localhost
  become: yes
  connection: local
  vars:
    host_metadata: "crm"
    zabbix_server_ip: "{{ monitor_ip }}"
    client_ip: "{{ ansible_default_ipv4.address }}"
    ubuntu_version: "{{ ansible_distribution_release }}"  # Zorg ervoor dat de juiste versie wordt gebruikt

  tasks:
    - name: Download Zabbix repository bestand
      get_url:
        url: "https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_7.0-2+ubuntu{{ ubuntu_version }}_all.deb"
        dest: "/tmp/zabbix-release_7.0-2+ubuntu{{ ubuntu_version }}_all.deb"

    - name: Voeg Zabbix repository toe
      apt:
        deb: "/tmp/zabbix-release_7.0-2+ubuntu{{ ubuntu_version }}_all.deb"

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Verwijder Zabbix repository bestand na installatie
      file:
        path: "/tmp/zabbix-release_7.0-2+ubuntu{{ ubuntu_version }}_all.deb"
        state: absent

    - name: Installeer Zabbix-agent
      apt:
        name: zabbix-agent
        state: present
